### ISSUE TITLE
Package lib, preprocessor e test

### ISSUE THREAD

**Issue by Desso95** [UNIPR-JSetL/JSetL#1]
Nella release 2.3b della libreria presente sul sito di JSetL sono presenti i sotto-package JSetL.lib, JSetL.preprocessor e JSetL.test, che invece non sono presenti nella versione inviata via mail. Sono ancora validi e posso semplicemente aggiungerli anche in questa versione?

[JSetL2.3b-sottopackage.zip](https://github.com/UNIPR-JSetL/JSetL/files/1088819/JSetL2.3b-sottopackage.zip)

**Comment by Desso95** [comment]
Eventualmente, nel package JSetL.test andrà incluso anche il test sui sorgenti di Lutero (in particolare della classe LMap)
[LMapTest.zip](https://github.com/UNIPR-JSetL/JSetL/files/1088898/LMapTest.zip)

**Comment by gfrossi** [comment]
Vanno senz'altro aggiunti i sottopackage JSetL.lib e JSetL.test. Lascerei invece fuori JSetL.preprocessor. 
Sì, nel package JSetL.test vanno aggiunti i test di Luturo ed eventuali altri nuovi.

**Comment by Desso95** [comment]
Sono stati effettuati i cambiamenti necessari nel commit 7cb7309 del 22/06/2017. Issue chiusa
