### ISSUE TITLE
Come gestire gli esempi?

### ISSUE THREAD

**Issue by Desso95** [UNIPR-JSetL/JSetL#2]
Sono stati prodotti alcuni codici di esempio per la libreria JSetL. Conviene includere anch'essi nella repository, magari in un sotto-package (JSetL.esempiArticoloSPE) o in una sotto cartella?

[esempiArticoloSPE.zip](https://github.com/UNIPR-JSetL/JSetL/files/1089140/esempiArticoloSPE.zip)

**Comment by gfrossi** [comment]
Sì, conviene includere anche uno o piu' gruppi di esempi. Credo sia meglio metterli in una sottocartella, fuori dal package JSetL.

**Comment by Desso95** [comment]
Magari in una repository a parte sempre sotto il controllo della stessa organizzazione (UNIPR-JSetL) ? (in modo che clonare la repository, ad esempio per un utente esterno, non significhi scaricare anche gli esempi, ma solo il codice necessario al funzionamento di JSetL)

**Comment by Desso95** [comment]
Magari in una repository a parte sempre sotto il controllo della stessa organizzazione (UNIPR-JSetL) ? (in modo che clonare la repository, ad esempio per un utente esterno, non significhi scaricare anche gli esempi, ma solo il codice necessario al funzionamento di JSetL)

**Comment by gfrossi** [comment]
Non e' possibile clonare solo una parte (una sottocartella) del repository? Comunque, non sarebbe un problema se un utente esterno quando scarica il package JSetL scaricasse anche gli esempi. Pero' JSetl e gli esempi dovrebbero risultare divisi in due cartelle distinte.

**Comment by Desso95** [comment]
Con il commit 5c0fff6, ho modificato la struttura della repository per poter includere gli esempi come cartella diversa dalla libreria JSetL. Sincronizzando in locale, potrebbe essere necessario aggiornare in Eclipse la posizione dei files sorgente (premendo il tasto F5). Nel caso ci fossero problemi, è possibile revertire il commit e pensare ad un'altra soluzione, viceversa la issue è chiusa.
